[package]
name = "scripty_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scripty_db = { path = "../scripty_db" }
scripty_config = { path = "../scripty_config" }
scripty_commands = { path = "../scripty_commands" }
