pct_stt_threads = 0.8
model_dir = "/home/user/stt_models"
token = "a.b.c"
support_invite = "https://discord.gg/xSpNJSjNhq"

[database]
host = "/var/run/postgresql/.s.PGSQL.5432"
# host = ["0.0.0.0", 5432]
user = "username"
password = "password"
database = "database"