pct_stt_threads = 0.8
model_dir = "/home/dustin/ds"
token = "ODExNjUyMTk5MTAwMzE3NzI2.YC1UBA.u6H5OLKwDUlFkv-AROCm2ruW-30"
support_invite = "https://discord.gg/xSpNJSjNhq"

[database]
host = "/var/run/postgresql/"
user = "scripty"
password = "scripty"
database = "scripty"