[package]
name = "scripty_audio_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7"
dashmap = "4"
tracing = "0.1"
songbird = "0.2"
async-trait = "0.1"
parking_lot = "0.12"
scripty_db = { path = "../scripty_db" }
scripty_audio = { path = "../scripty_audio" }
tokio = { version = "1.16", features = ["parking_lot"] }
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
