[package]
name = "scripty_audio_handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7"
dashmap = "3"
tracing = "0.1"
async-trait = "0.1"
parking_lot = "0.12"
scripty_db = { path = "../scripty_db" }
scripty_audio = { path = "../scripty_audio" }
tokio = { version = "1.16", features = ["parking_lot"] }
songbird = { git = "https://github.com/serenity-rs/songbird", branch = "next" }
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", features = [
  "tokio",
  "voice",
  "dashmap",
  "parking_lot",
  "rustls_backend",
  "native_tls_backend",
  "model",
  "gateway",
  "client",
  "cache",
  "builder",
  "collector",
  "utils",
], default-features = false }
sqlx = { version = "0.5", features = ["postgres", "macros", "migrate", "offline", "runtime-tokio-rustls"] }
