[package]
name = "scripty_commands"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4"
tracing = "0.1"
once_cell = "1.9"
scripty_db = { path = "../scripty_db" }
scripty_config = { path = "../scripty_config" }
poise = { git = "https://github.com/kangalioo/poise/" }
scripty_audio_handler = { path = "../scripty_audio_handler" }
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", features = [
  "tokio",
  "voice",
  "dashmap",
  "parking_lot",
  "rustls_backend",
  "native_tls_backend",
] }
